openapi: 3.0.0
info:
  title: 'Your API Title'
  description: 'Your API description'
  version: 1.0.0
paths:
  /api/games:
    get:
      tags:
        - Games
      summary: 'Get list of games'
      description: 'Returns list of games'
      operationId: getGamesList
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
components:
  schemas:
    Game:
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        publishing_date:
          type: string
          format: date
        category:
          type: string
      type: object
